import Head from "next/head";
import Summary from "../components/Summary";
import Latest from "../components/Latest";
import Menu from "../components/Menu";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";

const Homepage = () => {
  return (
    <div>
      <Head>
        <title>Paul Kindt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.io" />
      </Head>
      <Navbar />
      <Hero />
      <Latest />
      <Summary />
    </div>
  );
};

export default Homepage;
