import Head from 'next/head';
import Summary from '../components/Summary';
import Latest from '../components/Latest'
import Menu from '../components/Menu';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Paul Kindt</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel="icon" href="favicon.io" />
      </Head>
      <Menu />
    </div>
  );
};



export default Home;