import Head from 'next/head';

import Hero from '../components/Hero';
import Section from '../components/Section';
import Summary from '../components/Summary';


const Home = () => {
  return (
    <div>
      <Head>
        <title>Paul Kindt</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel="icon" href="favicon.io" />
      </Head>
      <Hero heading='Paul Kindt' message='Lorem Ipsum' />
      <Section />
      <Summary />
    </div>
  );
};



export default Home;