import Head from "next/head";
import Summary from "../components/Summary";
import Latest from "../components/Latest";
import Menu from "../components/Menu";

import Layout from "../components/Layout";
import NestedLayout from "../components/nested-layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Paul Kindt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.io" />
      </Head>
      <Menu />
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      <NestedLayout>{page}</NestedLayout>
    </Layout>
  );
};
